### ISSUE TITLE
BSONObj size: 19021871 (0x122402F) is invalid

### ISSUE THREAD

**Issue by bentiancai629** [irisnet/irishub-sync#210]
```
{"level":"warn","ts":"2020-01-08T14:29:53.266+0800","caller":"logger/logger.go:39","msg":"Create task fail","module":"CreateTask","err":"write tcp 192.168.1.184:51965->106.13.49.123:27017: i/o timeout"}
{"level":"error","ts":"2020-01-08T14:30:03.271+0800","caller":"logger/logger.go:44","msg":"Get executable task fail","module":"TaskExecutor","err":"read tcp 192.168.1.184:51965->106.13.49.123:27017: i/o timeout","stacktrace":"github.com/irisnet/irishub-sync/logger.Error\n\t/Users/bentiancai629/code/go/gopath/src/github.com/irisnet/irishub-sync/logger/zap_logger.go:56\ngithub.com/irisnet/irishub-sync/logger.Logger.Error\n\t/Users/bentiancai629/code/go/gopath/src/github.com/irisnet/irishub-sync/logger/logger.go:44\ngithub.com/irisnet/irishub-sync/service/task.executeTask\n\t/Users/bentiancai629/code/go/gopath/src/github.com/irisnet/irishub-sync/service/task/task_execute.go:85"}
{"level":"warn","ts":"2020-01-08T14:30:47.457+0800","caller":"logger/logger.go:39","msg":"Create task fail","module":"CreateTask","err":"BSONObj size: 19021871 (0x122402F) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: \"mgo_txn\""}

```
my mongoDB shell version is v4.2.1.  what does the error mean?

**Comment by kaifei-bianjie** [comment]
@bentiancai629 
- if you want to sync all data start with 0 height, you can use this release: [https://github.com/irisnet/irishub-sync/releases/tag/v0.16.3](https://github.com/irisnet/irishub-sync/releases/tag/v0.16.3)
- If you want to synchronizes irishub data from specify block height, please see detail: [https://github.com/irisnet/irishub-sync/blob/master/README.md](https://github.com/irisnet/irishub-sync/blob/master/README.md)

**Comment by bentiancai629** [comment]
> @bentiancai629
> 
> * if you want to sync all data start with 0 height, you can use this release: https://github.com/irisnet/irishub-sync/releases/tag/v0.16.3
> * If you want to synchronizes irishub data from specify block height, please see detail: https://github.com/irisnet/irishub-sync/blob/master/README.md

it works , thank you for your tips !

**Comment by bentiancai629** [comment]
> @bentiancai629
> 
> * if you want to sync all data start with 0 height, you can use this release: https://github.com/irisnet/irishub-sync/releases/tag/v0.16.3
> * If you want to synchronizes irishub data from specify block height, please see detail: https://github.com/irisnet/irishub-sync/blob/master/README.md

it works , thank you for your tips !
